<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('services')->delete();

        DB::table('services')->insert([
            [
                'name' => 'Linha Sobrancelha + Buço',
                'category' => 'Laser',
                'price' => 8.00,
                'recommended_price' => 8.00,
                'market_min' => 10.00,
                'market_avg' => 12.00,
                'market_max' => 15.00,
                'pricing_status' => 'Competitivo',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Mulher Zona Pequena',
                'category' => 'Laser',
                'price' => 20.00,
                'recommended_price' => 20.00,
                'market_min' => 12.00,
                'market_avg' => 16.00,
                'market_max' => 20.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Mulher Zona Média',
                'category' => 'Laser',
                'price' => 25.00,
                'recommended_price' => 25.00,
                'market_min' => 18.00,
                'market_avg' => 24.00,
                'market_max' => 30.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Mulher Zona Grande',
                'category' => 'Laser',
                'price' => 45.00,
                'recommended_price' => 45.00,
                'market_min' => 29.00,
                'market_avg' => 45.00,
                'market_max' => 60.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Homem Zona Pequena',
                'category' => 'Laser',
                'price' => 25.00,
                'recommended_price' => 25.00,
                'market_min' => 15.00,
                'market_avg' => 20.00,
                'market_max' => 25.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Homem Zona Média',
                'category' => 'Laser',
                'price' => 30.00,
                'recommended_price' => 30.00,
                'market_min' => 20.00,
                'market_avg' => 30.00,
                'market_max' => 40.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Homem Zona Grande',
                'category' => 'Laser',
                'price' => 60.00,
                'recommended_price' => 60.00,
                'market_min' => 40.00,
                'market_avg' => 55.00,
                'market_max' => 70.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Pack 6 Sessões',
                'category' => 'Drenagem',
                'price' => 180.00,
                'recommended_price' => 180.00,
                'market_min' => 180.00,
                'market_avg' => 240.00,
                'market_max' => 300.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Drenagem Média',
                'category' => 'Drenagem',
                'price' => 45.00,
                'recommended_price' => 45.00,
                'market_min' => 30.00,
                'market_avg' => 38.00,
                'market_max' => 45.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Drenagem Completa',
                'category' => 'Drenagem',
                'price' => 55.00,
                'recommended_price' => 55.00,
                'market_min' => 45.00,
                'market_avg' => 55.00,
                'market_max' => 65.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Relaxamento 30\'',
                'category' => 'Massagens',
                'price' => 30.00,
                'recommended_price' => 30.00,
                'market_min' => 25.00,
                'market_avg' => 30.00,
                'market_max' => 35.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Relaxamento 60\'',
                'category' => 'Massagens',
                'price' => 60.00,
                'recommended_price' => 60.00,
                'market_min' => 45.00,
                'market_avg' => 55.00,
                'market_max' => 70.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Desportiva 30\'',
                'category' => 'Massagens',
                'price' => 45.00,
                'recommended_price' => 45.00,
                'market_min' => 35.00,
                'market_avg' => 42.00,
                'market_max' => 50.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Desportiva 60\'',
                'category' => 'Massagens',
                'price' => 65.00,
                'recommended_price' => 65.00,
                'market_min' => 50.00,
                'market_avg' => 60.00,
                'market_max' => 80.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Terapêutica 30\'',
                'category' => 'Massagens',
                'price' => 40.00,
                'recommended_price' => 40.00,
                'market_min' => 30.00,
                'market_avg' => 40.00,
                'market_max' => 50.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Terapêutica 60\'',
                'category' => 'Massagens',
                'price' => 65.00,
                'recommended_price' => 65.00,
                'market_min' => 50.00,
                'market_avg' => 60.00,
                'market_max' => 80.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Revitalizante Corpo Inteiro',
                'category' => 'Massagens',
                'price' => 65.00,
                'recommended_price' => 65.00,
                'market_min' => 50.00,
                'market_avg' => 65.00,
                'market_max' => 80.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Grávidas',
                'category' => 'Massagens',
                'price' => 60.00,
                'recommended_price' => 60.00,
                'market_min' => 45.00,
                'market_avg' => 60.00,
                'market_max' => 75.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Relaxamento a 4 Mãos',
                'category' => 'Massagens',
                'price' => 60.00,
                'recommended_price' => 85.00,
                'market_min' => 80.00,
                'market_avg' => 115.00,
                'market_max' => 150.00,
                'pricing_status' => 'Rever',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Remoção S',
                'category' => 'Tatuagem',
                'price' => 25.00,
                'recommended_price' => 40.00,
                'market_min' => 60.00,
                'market_avg' => 75.00,
                'market_max' => 90.00,
                'pricing_status' => 'Rever',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Remoção M',
                'category' => 'Tatuagem',
                'price' => 35.00,
                'recommended_price' => 60.00,
                'market_min' => 90.00,
                'market_avg' => 115.00,
                'market_max' => 140.00,
                'pricing_status' => 'Rever',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Remoção L',
                'category' => 'Tatuagem',
                'price' => 45.00,
                'recommended_price' => 80.00,
                'market_min' => 140.00,
                'market_avg' => 170.00,
                'market_max' => 200.00,
                'pricing_status' => 'Rever',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Remoção XL',
                'category' => 'Tatuagem',
                'price' => 55.00,
                'recommended_price' => 120.00,
                'market_min' => 150.00,
                'market_avg' => 225.00,
                'market_max' => 300.00,
                'pricing_status' => 'Rever',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Esfoliação Corporal',
                'category' => 'Corporais',
                'price' => 40.00,
                'recommended_price' => 40.00,
                'market_min' => 30.00,
                'market_avg' => 45.00,
                'market_max' => 65.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Anti-Celulite',
                'category' => 'Corporais',
                'price' => 40.00,
                'recommended_price' => 45.00,
                'market_min' => 45.00,
                'market_avg' => 60.00,
                'market_max' => 80.00,
                'pricing_status' => 'Rever',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Firmeza',
                'category' => 'Corporais',
                'price' => 40.00,
                'recommended_price' => 40.00,
                'market_min' => 40.00,
                'market_avg' => 60.00,
                'market_max' => 80.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Redutor',
                'category' => 'Corporais',
                'price' => 40.00,
                'recommended_price' => 40.00,
                'market_min' => 40.00,
                'market_avg' => 60.00,
                'market_max' => 80.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Estrias',
                'category' => 'Corporais',
                'price' => 60.00,
                'recommended_price' => 60.00,
                'market_min' => 50.00,
                'market_avg' => 75.00,
                'market_max' => 100.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Reflexologia dos Pés',
                'category' => 'Corporais',
                'price' => 25.00,
                'recommended_price' => 30.00,
                'market_min' => 30.00,
                'market_avg' => 40.00,
                'market_max' => 50.00,
                'pricing_status' => 'Rever',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Cavitação Body',
                'category' => 'Corporais',
                'price' => 40.00,
                'recommended_price' => 40.00,
                'market_min' => 40.00,
                'market_avg' => 60.00,
                'market_max' => 80.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Radiofrequência Body',
                'category' => 'Corporais',
                'price' => 35.00,
                'recommended_price' => 40.00,
                'market_min' => 25.00,
                'market_avg' => 45.00,
                'market_max' => 65.00,
                'pricing_status' => 'Rever',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Design Sobrancelha',
                'category' => 'Faciais',
                'price' => 10.00,
                'recommended_price' => 10.00,
                'market_min' => 10.00,
                'market_avg' => 15.00,
                'market_max' => 20.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Lifting Pestanas',
                'category' => 'Faciais',
                'price' => 30.00,
                'recommended_price' => 30.00,
                'market_min' => 30.00,
                'market_avg' => 35.00,
                'market_max' => 40.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Brow Lamination',
                'category' => 'Faciais',
                'price' => 30.00,
                'recommended_price' => 30.00,
                'market_min' => 25.00,
                'market_avg' => 32.00,
                'market_max' => 40.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Limpeza Pele',
                'category' => 'Faciais',
                'price' => 20.00,
                'recommended_price' => 20.00,
                'market_min' => 25.00,
                'market_avg' => 40.00,
                'market_max' => 60.00,
                'pricing_status' => 'Competitivo',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Limpeza Pele Premium',
                'category' => 'Faciais',
                'price' => 35.00,
                'recommended_price' => 35.00,
                'market_min' => 35.00,
                'market_avg' => 50.00,
                'market_max' => 70.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Limpeza Pele + BB Glow',
                'category' => 'Faciais',
                'price' => 40.00,
                'recommended_price' => 40.00,
                'market_min' => 40.00,
                'market_avg' => 60.00,
                'market_max' => 90.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Peeling Anti-Acne',
                'category' => 'Faciais',
                'price' => 50.00,
                'recommended_price' => 50.00,
                'market_min' => 40.00,
                'market_avg' => 65.00,
                'market_max' => 90.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Peeling Anti-Idade',
                'category' => 'Faciais',
                'price' => 50.00,
                'recommended_price' => 50.00,
                'market_min' => 40.00,
                'market_avg' => 65.00,
                'market_max' => 90.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Microagulhamento Anti-Idade',
                'category' => 'Faciais',
                'price' => 70.00,
                'recommended_price' => 70.00,
                'market_min' => 60.00,
                'market_avg' => 90.00,
                'market_max' => 120.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Microagulhamento Despigmentante',
                'category' => 'Faciais',
                'price' => 70.00,
                'recommended_price' => 70.00,
                'market_min' => 60.00,
                'market_avg' => 90.00,
                'market_max' => 120.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Microagulhamento Papada',
                'category' => 'Faciais',
                'price' => 70.00,
                'recommended_price' => 70.00,
                'market_min' => 60.00,
                'market_avg' => 90.00,
                'market_max' => 120.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Exossomas',
                'category' => 'Faciais',
                'price' => 90.00,
                'recommended_price' => 120.00,
                'market_min' => 120.00,
                'market_avg' => 185.00,
                'market_max' => 250.00,
                'pricing_status' => 'Rever',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Radiofrequência Face',
                'category' => 'Faciais',
                'price' => 30.00,
                'recommended_price' => 30.00,
                'market_min' => 30.00,
                'market_avg' => 45.00,
                'market_max' => 60.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Bio Radiofrequência Face',
                'category' => 'Faciais',
                'price' => 20.00,
                'recommended_price' => 35.00,
                'market_min' => 35.00,
                'market_avg' => 50.00,
                'market_max' => 70.00,
                'pricing_status' => 'Rever',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Manicure Japonesa',
                'category' => 'Manicure',
                'price' => 25.00,
                'recommended_price' => 25.00,
                'market_min' => 20.00,
                'market_avg' => 28.00,
                'market_max' => 35.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Maquilhagem Simples',
                'category' => 'Beleza',
                'price' => 15.00,
                'recommended_price' => 15.00,
                'market_min' => 15.00,
                'market_avg' => 22.00,
                'market_max' => 30.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Maquilhagem Básica',
                'category' => 'Beleza',
                'price' => 20.00,
                'recommended_price' => 20.00,
                'market_min' => 20.00,
                'market_avg' => 30.00,
                'market_max' => 40.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Maquilhagem Elaborada',
                'category' => 'Beleza',
                'price' => 30.00,
                'recommended_price' => 30.00,
                'market_min' => 30.00,
                'market_avg' => 45.00,
                'market_max' => 60.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Mulher Zona Pequena',
                'category' => 'Cera',
                'price' => 10.00,
                'recommended_price' => 10.00,
                'market_min' => 8.00,
                'market_avg' => 12.00,
                'market_max' => 15.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Mulher Zona Média',
                'category' => 'Cera',
                'price' => 15.00,
                'recommended_price' => 15.00,
                'market_min' => 12.00,
                'market_avg' => 18.00,
                'market_max' => 25.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Mulher Zona Grande',
                'category' => 'Cera',
                'price' => 25.00,
                'recommended_price' => 25.00,
                'market_min' => 20.00,
                'market_avg' => 30.00,
                'market_max' => 40.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Homem Zona Pequena',
                'category' => 'Cera',
                'price' => 15.00,
                'recommended_price' => 15.00,
                'market_min' => 12.00,
                'market_avg' => 16.00,
                'market_max' => 20.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Homem Zona Média',
                'category' => 'Cera',
                'price' => 25.00,
                'recommended_price' => 25.00,
                'market_min' => 20.00,
                'market_avg' => 28.00,
                'market_max' => 35.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ],
            [
                'name' => 'Homem Zona Grande',
                'category' => 'Cera',
                'price' => 45.00,
                'recommended_price' => 45.00,
                'market_min' => 35.00,
                'market_avg' => 48.00,
                'market_max' => 60.00,
                'pricing_status' => 'Alinhado',
                'duration_minutes' => 60,
                'active' => true,
            ]
        ]);
    }
}
